### ISSUE TITLE
Not report the error when prettier fails.

### ISSUE THREAD

**Issue by Jancat** [ikatyang/tslint-plugin-prettier#233]
The code below will be an error in VSCode editor by **prettier** `semi: false` rule:

```
import foo from 'src/demo.ts';
             ~~ [tslint] Delete `;` (prettier)
```

But the command `tslint -c tslint.yaml src/**/*.ts` not report the prettier error, and done successfully.

**tslint.yaml**
```yaml
extends:
  - 'tslint:latest'
  - tslint-eslint-rules
  - tslint-config-prettier
defaultSeverity: error
rulesDirectory: tslint-plugin-prettier
rules:
  prettier: true
  ....
```

**.prettierrc.yml**
```yaml
printWidth: 100
useTabs: false
tabWidth: 2
semi: false
singleQuote: true
trailingComma: 'all'
bracketSpacing: true
arrowParens: 'avoid'
```
